# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      rust-dependencies:
        update-types:
          - "minor"
          - "patch"
    ignore:
      # MSRV: these deps use edition 2025 in their newest versions.
      # Once the MSRV reaches 1.85 these can be updated and unignored.
      - dependency-name: ignore
      - dependency-name: globset
      - dependency-name: grep-matcher

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
